# Generated by Django 5.1.2 on 2024-10-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundoVerde', '0003_alter_producto_precio_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
